### PR TITLE
Fixed Bug #8 

### PR DESCRIPTION
**Pull request by krishnenduATU**
Fixed bug in circumference formula in calculate_circumference.py

### CODE REVIEW

**Review by krishnenduvp — APPROVED** [review]
Reviewed the scripts, all good for production.

**Review by krishnenduATU — COMMENTED** [review]
Approved

**Review by krishnenduvp — APPROVED** [review]
Viewed all scripts, approved

**Review by krishnenduATU — COMMENTED** [review]
Viewed

**Review by krishnenduvp — APPROVED** [review]

**Review by krishnenduvp — APPROVED** [review]

**Pull request merged**
